---

# Better method but SSL is not yet supported on kubernetes module in Ansible v2.2
#- name: create k8s DNS service and replication controller
#  kubernetes:
#    api_endpoint: "{{ groups['k8s-workers'] | map('extract', hostvars, ['priv_ip']) | list | random }}"
#    inline_data: "{{item}}"
#    state: present
#  with_items:
#    - "{{k8s_dns_service}}"
#    - "{{k8s_dns_replication_controller}}"

- name: generate k8s DNS service and replication controller files
  template:
    src: "{{k8s_template_dir}}/generate_yaml.j2"
    dest: "/tmp/{{item.dest}}"
    mode: 0644
  with_items:
    - { yaml: "{{k8s_dns_service}}", dest: 'kube-dns-svc.yaml' }
    - { yaml: "{{k8s_dns_replication_controller}}", dest: 'kube-dns-rc.yaml' }

- name: create k8s DNS service and replication controller
  command: "{{item}}"
  with_items:
    - "/opt/bin/kubectl apply -f /tmp/kube-dns-rc.yaml"
    - "/opt/bin/kubectl apply -f /tmp/kube-dns-svc.yaml"
   changed_when: false