---

# SSL certificates
- include: k8s_ssl_deploy.yml

# Network Configuration
- include: k8s_networking.yml

# Docker Configuration
- include: k8s_docker.yml

# Setup Server / Proxy / Controller Manager / Scheduler
- include: k8s_master_nodes_components.yml

# Create the kubelet Unit
- include: k8s_kubelet.yml